import os

# BYBIT
BYBIT_DWH_PATH = "dwh/bybit/"
BYBIT_CONFIG_PATH = "configs/bybit/"
BYBIT_DEMO_API_KEY = os.getenv("ENV_VAR_BYBIT_DEMO_API_KEY")
BYBIT_DEMO_API_SECRET = os.getenv("ENV_VAR_BYBIT_DEMO_API_SECRET")
